=== Cytooxien/Cytooxien-Missions/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Quest",
  "type": "object",
  "required": [
    "id"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "Der Name der Quest muss innerhalb eines Bundles eindeutig sein."
    },
    "displayName": {
      "type": "string",
      "description": "Der Anzeigename der Quest"
    },
    "description": {
      "type": "string",
      "description": "Eine ausführlichere Beschreibung der Quest."
    },
    "stages": {
      "type": "array",
      "items": {
        "type": "object",
        "minItems": 1,
        "properties": {
          "objectives": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/$defs/objective"
            }
          },
          "rewards": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/reward"
            }
          }
        }
      }
    },
    "requirements": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/requirement"
      }
    },
    "rewards": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/reward"
      }
    },
    "options": {
      "type": "object",
      "description": "Optionale Einstellungen für die Mission",
      "properties": {
        "display": {
          "description": "Anzeige Item",
          "type": "string"
        },
        "bossBar": {
          "description": "Soll die BossBar während der Mission angezeigt werden",
          "type": "boolean"
        }
      }
    }
  },
  "$defs": {
    "reward": {
      "type": "object",
      "title": "Reward",
      "required": [
        "id",
        "type"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Name der Belohnung"
        },
        "displayName": {
          "type": "string",
          "description": "Optionaler Anzeigename"
        },
        "type": {
          "type": "string",
          "description": "Beschreibung des Handlers für die Implementierung",
          "enum": [
            "ItemStackReward",
            "TransactionReward"
          ]
        },
        "options": {
          "type": "object",
          "description": "Optionale Einstellungen abhängig von dem Reward Typ"
        }
      }
    },
    "requirement": {
      "type": "object",
      "title": "Requirement",
      "required": [
        "id",
        "type"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Eindeutige Id"
        },
        "displayName": {
          "type": "string",
          "description": "Optionaler Anzeigename"
        },
        "checkOnlyAtStart": {
          "type": "boolean",
          "description": "Soll die Voraussetzung nur beim start der Quest validiert werden."
        },
        "type": {
          "type": "string",
          "description": "Beschreibung des Handlers für die Implementierung",
          "enum": [
            "QuestCompletedRequirement",
            "AccessLevelRequirement"
          ]
        },
        "options": {
          "type": "object",
          "description": "Optionale Einstellungen abhängig von dem Requirement Typ"
        }
      }
    },
    "objective": {
      "type": "object",
      "title": "Objective",
      "required": [
        "id",
        "goal",
        "type"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Eindeutiger Name innerhalb einer Stage"
        },
        "displayName": {
          "type": "string",
          "description": "Optionaler Anzeigename der Aufgabe"
        },
        "goal": {
          "type": "integer",
          "description": "Der maximale Wert (Ziel), der erreicht werden kann."
        },
        "type": {
          "type": "string",
          "description": "Beschreibung des Handlers für die Implementierung",
          "enum": [
            "BreakBlockObjective",
            "PlaceBlockObjective",
            "KillEntityObjective",
            "BreedEntityObjective",
            "FishItemObjective",
            "HandInItemObjective",
            "TalkToNPCObjective",
            "ActionEventObjective",
            "CraftItemObjective"
          ]
        },
        "options": {
          "type": "object",
          "description": "Optionale Einstellungen abhängig von dem Objective Typ",
          "properties": {
            "display": {
              "description": "Anzeige Item",
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== Cytooxien/Cytooxien-Missions/quests/siegfried/2f_mobs.json
{
  "id": "2f_mobs",
  "displayName": "Monsterjagd",
  "description": "Rüste dich aus und helfe ein paar fiese Monster zu bekämpfen!",
  "options": {
    "display": "zombie_head"
  },
  "stages": [
    {
      "objectives": [
        {
          "id": "kill_creeper",
          "displayName": "Töte 5 Creeper",
          "goal": 5,
          "type": "KillEntityObjective",
          "options": {
            "display": "creeper_head",
            "entities": [
              "minecraft:creeper"
            ]
          }
        },
        {
          "id": "kill_zombie",
          "displayName": "Töte 10 Zombies",
          "goal": 10,
          "type": "KillEntityObjective",
          "options": {
            "display": "zombie_head",
            "entities": [
              "minecraft:zombie"
            ]
          }
        },
        {
          "id": "collect_bones",
          "displayName": "Bringe mir 10 Knochen",
          "goal": 10,
          "type": "HandInItemObjective",
          "options": {
            "display": "bone",
            "blocks": [
              "minecraft:bone"
            ]
          }
        },
        {
          "id": "collect_spidereye",
          "displayName": "Bringe mir 10 Spinnenaugen",
          "goal": 10,
          "type": "HandInItemObjective",
          "options": {
            "display": "spider_eye",
            "blocks": [
              "minecraft:spider_eye"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [
    {
      "id": "req_1",
      "type": "QuestCompletedRequirement",
      "options": {
        "quests": [
          "1a_ressources",
          "1b_iron"
        ]
      }
    }
  ],
  "rewards": [
    {
      "id": "moneyreward",
      "displayName": "45 Münzen",
      "type": "TransactionReward",
      "options": {
        "amount": 45.0
      }
    }
  ]
}

=== Cytooxien/Cytooxien-Missions/quests/siegfried/2d_home.json
{
  "id": "2d_home",
  "displayName": "Dein eigenes Heim",
  "description": "Errichte dein erstes eigenes Heim.",
  "options": {
    "display": "red_bed"
  },
  "stages": [
    {
      "objectives": [
        {
          "id": "place_door",
          "displayName": "Platziere eine Eingangstür!",
          "goal": 1,
          "type": "PlaceBlockObjective",
          "options": {
            "display": "spruce_door",
            "blocks": [
              "#minecraft:wooden_doors"
            ]
          }
        },
        {
          "id": "craft_bed",
          "displayName": "Baue dir ein Bett!",
          "goal": 1,
          "type": "CraftItemObjective",
          "options": {
            "display": "red_bed",
            "items": [
              "#minecraft:beds"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [
    {
      "id": "req_1",
      "type": "QuestCompletedRequirement",
      "options": {
        "quests": [
          "1a_ressources",
          "1b_iron"
        ]
      }
    }
  ],
  "rewards": [
    {
      "id": "moneyreward",
      "displayName": "20 Münzen",
      "type": "TransactionReward",
      "options": {
        "amount": 20.0
      }
    }
  ]
}

=== Cytooxien/Cytooxien-Missions/quests/siegfried/2c_wheat.json
{
  "id": "2c_wheat",
  "displayName": "Die erste Ernte",
  "description": "Beweise einen gr체nden Daumen und lege auf deinem Grundst체ck ein Feld an.",
  "options": {
    "display": "wheat"
  },
  "stages": [
    {
      "objectives": [
        {
          "id": "plant_seeds",
          "displayName": "Pflanze 10x Weizensamen ein!",
          "goal": 10,
          "type": "PlaceBlockObjective",
          "options": {
            "display": "wheat_seeds",
            "blocks": [
              "minecraft:wheat"
            ]
          }
        },
        {
          "id": "break_wheat",
          "displayName": "Ernte 10x ausgewachsenes Weizen ab!",
          "goal": 10,
          "type": "BreakBlockObjective",
          "options": {
            "display": "iron_hoe",
            "blocks": [
              "minecraft:wheat[age=7]"
            ]
          }
        },
        {
          "id": "plant_trees",
          "displayName": "Pflanze 5 B채ume an!",
          "goal": 5,
          "type": "PlaceBlockObjective",
          "options": {
            "display": "oak_sapling",
            "blocks": [
              "#minecraft:saplings"
            ]
          }
        },
        {
          "id": "collect_flowers",
          "displayName": "Bringe mir 20 Blumen!",
          "goal": 20,
          "type": "HandInItemObjective",
          "options": {
            "display": "poppy",
            "blocks": [
              "#minecraft:flowers"
            ]
          }
        },
        {
          "id": "collect_sugarcane",
          "displayName": "Bringe mir 10x Zuckerrohr!",
          "goal": 10,
          "type": "HandInItemObjective",
          "options": {
            "display": "sugarcane",
            "blocks": [
              "minecraft:sugarcane"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [
    {
      "id": "req_1",
      "type": "QuestCompletedRequirement",
      "options": {
        "quests": [
          "1a_ressources",
          "1b_iron"
        ]
      }
    }
  ],
  "rewards": [
    {
      "id": "moneyreward",
      "displayName": "70 M체nzen",
      "type": "TransactionReward",
      "options": {
        "amount": 70.0
      }
    }
  ]
}

=== Cytooxien/Cytooxien-Missions/quests/siegfried/1a_ressources.json
{
  "id": "1a_ressources",
  "displayName": "An die Arbeit",
  "description": "Baue in den Farmwelten ein paar Ressourcen ab.",
  "options": {
    "display": "wooden_axe"
  },
  "stages": [
    {
      "objectives": [
        {
          "id": "break_wood",
          "displayName": "Baue 16 Holzstämme ab!",
          "goal": 16,
          "type": "BreakBlockObjective",
          "options": {
            "display": "oak_log",
            "blocks": [
              "#minecraft:logs"
            ]
          }
        },
        {
          "id": "break_stone",
          "displayName": "Baue 64 Steine ab!",
          "goal": 64,
          "type": "BreakBlockObjective",
          "options": {
            "display": "cobblestone",
            "blocks": [
              "#minecraft:base_stone_overworld"
            ]
          }
        },
        {
          "id": "break_coal",
          "displayName": "Baue 16 Kohle ab!",
          "goal": 16,
          "type": "BreakBlockObjective",
          "options": {
            "display": "coal",
            "blocks": [
              "minecraft:coal_ore",
              "minecraft:deepslate_coal_ore"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [],
  "rewards": [
    {
      "id": "moneyreward",
      "displayName": "30 Münzen",
      "type": "TransactionReward",
      "options": {
        "amount": 30.0
      }
    }
  ]
}

=== Cytooxien/Cytooxien-Missions/quests/siegfried/1b_iron.json
{
  "id": "1b_iron",
  "displayName": "Rüste dich aus",
  "description": "Begebe dich auf die Suche nach Eisen und rüste dich damit aus.",
  "options": {
    "display": "iron_pickaxe"
  },
  "stages": [
    {
      "objectives": [
        {
          "id": "break_iron",
          "displayName": "Finde 20x Eisen!",
          "goal": 20,
          "type": "BreakBlockObjective",
          "options": {
            "display": "iron_ingot",
            "blocks": [
              "#minecraft:iron_ores"
            ]
          }
        },
        {
          "id": "craft_pickaxe",
          "displayName": "Crafte dir eine Eisen-Spitzhacke",
          "goal": 1,
          "type": "CraftItemObjective",
          "options": {
            "display": "iron_pickaxe",
            "items": [
              "minecraft:iron_pickaxe"
            ]
          }
        },
        {
          "id": "craft_axe",
          "displayName": "Crafte dir eine Eisen-Axt",
          "goal": 1,
          "type": "CraftItemObjective",
          "options": {
            "display": "iron_axe",
            "items": [
              "minecraft:iron_axe"
            ]
          }
        },
        {
          "id": "craft_shovel",
          "displayName": "Crafte dir eine Eisen-Schaufel",
          "goal": 1,
          "type": "CraftItemObjective",
          "options": {
            "display": "iron_shovel",
            "items": [
              "minecraft:iron_shovel"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [],
  "rewards": [
    {
      "id": "moneyreward",
      "displayName": "30 Münzen",
      "type": "TransactionReward",
      "options": {
        "amount": 30.0
      }
    }
  ]
}

=== Cytooxien/Cytooxien-Missions/quests/siegfried/2g_nether.json
{
  "id": "2g_nether",
  "displayName": "In die Unterwelt",
  "description": "Begebe dich in die Hölle für ein paar gefährliche Besorgungen.",
  "options": {
    "display": "blaze_rod"
  },
  "stages": [
    {
      "objectives": [
        {
          "id": "break_obsidian",
          "displayName": "Baue 10 Obsidian für ein Portal ab!",
          "goal": 10,
          "type": "BreakBlockObjective",
          "options": {
            "display": "obsidian",
            "blocks": [
              "minecraft:obsidian"
            ]
          }
        },
        {
          "id": "craft_flintsteel",
          "displayName": "Crafte dir ein Feuerzeug!",
          "goal": 1,
          "type": "CraftItemObjective",
          "options": {
            "display": "flint_and_steel",
            "items": [
              "minecraft:flint_and_steel"
            ]
          }
        },
        {
          "id": "break_netherquartz",
          "displayName": "Baue 32 Netzerquarz ab!",
          "goal": 32,
          "type": "BreakBlockObjective",
          "options": {
            "display": "nether_quartz",
            "blocks": [
              "minecraft:nether_quartz_ore"
            ]
          }
        },
        {
          "id": "break_glowstone",
          "displayName": "Baue 16 Glowstone ab!",
          "goal": 16,
          "type": "BreakBlockObjective",
          "options": {
            "display": "glowstone",
            "blocks": [
              "minecraft:glowstone"
            ]
          }
        },
        {
          "id": "collect_netherwart",
          "displayName": "Bringe mir 10 Netherwarzen!",
          "goal": 10,
          "type": "HandInItemObjective",
          "options": {
            "display": "nether_wart",
            "blocks": [
              "minecraft:nether_wart"
            ]
          }
        },
        {
          "id": "collect_blazerod",
          "displayName": "Bringe mir eine Lohenrute!",
          "goal": 1,
          "type": "HandInItemObjective",
          "options": {
            "display": "blaze_rod",
            "blocks": [
              "minecraft:blaze_rod"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [
    {
      "id": "req_1",
      "type": "QuestCompletedRequirement",
      "options": {
        "quests": [
          "1a_ressources",
          "1b_iron"
        ]
      }
    }
  ],
  "rewards": [
    {
      "id": "moneyreward",
      "displayName": "100 Münzen",
      "type": "TransactionReward",
      "options": {
        "amount": 100.0
      }
    }
  ]
}

=== Cytooxien/Cytooxien-Missions/quests/exampleBundle/example2.json
{
  "id": "exampleQuest2",
  "displayName": "Held der Steine TM",
  "description": "Held der Steine TM",
  "stages": [
    {
      "objectives": [
        {
          "id": "handIn1",
          "displayName": "Gebe 10 Steine ab",
          "goal": 10,
          "type": "HandInItemObjective",
          "options": {
            "items": [
              "minecraft:stone"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [
    {
      "id": "missionCompleted",
      "displayName": "Abgeschlossene Missionen",
      "type": "QuestCompletedRequirement",
      "options": {
        "quests": [
          "exampleQuest1"
        ]
      }
    }
  ],
  "rewards": [
    {
      "id": "diamondReward",
      "displayName": "1x Diamant",
      "type": "ItemStackReward",
      "options": {
        "items": [
          "DIAMOND"
        ]
      }
    }
  ]
}

=== Cytooxien/Cytooxien-Missions/quests/exampleBundle/example1.json
{
  "id": "exampleQuest1",
  "displayName": "Beispiel Quest 1",
  "description": "Farme Stein Blöcke",
  "stages": [
    {
      "objectives": [
        {
          "id": "break10Stone",
          "displayName": "Baue 10 Steinblöcke ab.",
          "goal": 10,
          "type": "BreakBlockObjective",
          "options": {
            "blocks": [
              "minecraft:stone"
            ]
          }
        }
      ]
    },
    {
      "objectives": [
        {
          "id": "break20Stone",
          "displayName": "Baue 20 Steinblöcke ab.",
          "goal": 20,
          "type": "BreakBlockObjective",
          "options": {
            "blocks": [
              "minecraft:stone"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [],
  "rewards": [
    {
      "id": "diamondReward",
      "displayName": "1x Diamant",
      "type": "ItemStackReward",
      "options": {
        "items": [
          "{DataVersion:2586,id:\"minecraft:diamond\",Count:1b}"
        ]
      }
    }
  ]
}
