=== Cytooxien/Cytooxien-Missions/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Quest",
  "type": "object",
  "required": [
    "id"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "Der Name der Quest muss innerhalb eines Bundles eindeutig sein."
    },
    "displayName": {
      "type": "string",
      "description": "Der Anzeigename der Quest"
    },
    "description": {
      "type": "string",
      "description": "Eine ausführlichere Beschreibung der Quest."
    },
    "stages": {
      "type": "array",
      "items": {
        "type": "object",
        "minItems": 1,
        "properties": {
          "objectives": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "#/$defs/objective"
            }
          },
          "rewards": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/reward"
            }
          }
        }
      }
    },
    "requirements": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/requirement"
      }
    },
    "rewards": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/reward"
      }
    },
    "options": {
      "type": "object",
      "description": "Optionale Einstellungen für die Mission",
      "properties": {
        "display": {
          "description": "Anzeige Item",
          "type": "string"
        },
        "bossBar": {
          "description": "Soll die BossBar während der Mission angezeigt werden",
          "type": "boolean"
        }
      }
    }
  },
  "$defs": {
    "reward": {
      "type": "object",
      "title": "Reward",
      "required": [
        "id",
        "type"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Name der Belohnung"
        },
        "displayName": {
          "type": "string",
          "description": "Optionaler Anzeigename"
        },
        "type": {
          "type": "string",
          "description": "Beschreibung des Handlers für die Implementierung",
          "enum": [
            "ItemStackReward",
            "TransactionReward"
          ]
        },
        "options": {
          "type": "object",
          "description": "Optionale Einstellungen abhängig von dem Reward Typ"
        }
      }
    },
    "requirement": {
      "type": "object",
      "title": "Requirement",
      "required": [
        "id",
        "type"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Eindeutige Id"
        },
        "displayName": {
          "type": "string",
          "description": "Optionaler Anzeigename"
        },
        "checkOnlyAtStart": {
          "type": "boolean",
          "description": "Soll die Voraussetzung nur beim start der Quest validiert werden."
        },
        "type": {
          "type": "string",
          "description": "Beschreibung des Handlers für die Implementierung",
          "enum": [
            "QuestCompletedRequirement",
            "AccessLevelRequirement"
          ]
        },
        "options": {
          "type": "object",
          "description": "Optionale Einstellungen abhängig von dem Requirement Typ"
        }
      }
    },
    "objective": {
      "type": "object",
      "title": "Objective",
      "required": [
        "id",
        "goal",
        "type"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Eindeutiger Name innerhalb einer Stage"
        },
        "displayName": {
          "type": "string",
          "description": "Optionaler Anzeigename der Aufgabe"
        },
        "goal": {
          "type": "integer",
          "description": "Der maximale Wert (Ziel), der erreicht werden kann."
        },
        "type": {
          "type": "string",
          "description": "Beschreibung des Handlers für die Implementierung",
          "enum": [
            "BreakBlockObjective",
            "PlaceBlockObjective",
            "KillEntityObjective",
            "BreedEntityObjective",
            "FishItemObjective",
            "HandInItemObjective",
            "TalkToNPCObjective",
            "ActionEventObjective",
            "CraftItemObjective"
          ]
        },
        "options": {
          "type": "object",
          "description": "Optionale Einstellungen abhängig von dem Objective Typ",
          "properties": {
            "display": {
              "description": "Anzeige Item",
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== Cytooxien/Cytooxien-Missions/quests/siegfried/2b_animals.json
{
  "id": "2b_animals",
  "displayName": "Tierzucht",
  "description": "Suche in der Farmwelt nach Tieren und beginne mit einer Hühnerzucht.",
  "options": {
    "display": "egg"
  },
  "stages": [
    {
      "objectives": [
        {
          "id": "kill_pigs",
          "displayName": "Töte 5 Schweine!",
          "goal": 5,
          "type": "KillEntityObjective",
          "options": {
            "display": "{DataVersion:2586,id:\"minecraft:player_head\",tag:{Damage:3,display:{Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"blue\",\"text\":\"Pig\"}],\"text\":\"\"}'},SkullOwner:{Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjIxNjY4ZWY3Y2I3OWRkOWMyMmNlM2QxZjNmNGNiNmUyNTU5ODkzYjZkZjRhNDY5NTE0ZTY2N2MxNmFhNCJ9fX0=\"}]},Id:[I;67411088,-739686879,-1666252800,11182903]}},Count:1b}",
            "entities": [
              "minecraft:pig"
            ]
          }
        },
        {
          "id": "kill_cows",
          "displayName": "Töte 5 Kühe!",
          "goal": 5,
          "type": "KillEntityObjective",
          "options": {
            "display": "{DataVersion:2586,id:\"minecraft:player_head\",tag:{Damage:3,display:{Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"blue\",\"text\":\"Cow\"}],\"text\":\"\"}'},SkullOwner:{Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWQ2YzZlZGE5NDJmN2Y1ZjcxYzMxNjFjNzMwNmY0YWVkMzA3ZDgyODk1ZjlkMmIwN2FiNDUyNTcxOGVkYzUifX19\"}]},Id:[I;67411088,-739686879,-1666252800,11182901]}},Count:1b}",
            "entities": [
              "minecraft:cow"
            ]
          }
        },
        {
          "id": "kill_sheeps",
          "displayName": "Töte 5 Schafe!",
          "goal": 5,
          "type": "KillEntityObjective",
          "options": {
            "display": "{DataVersion:2586,id:\"minecraft:player_head\",tag:{Damage:3,display:{Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"blue\",\"text\":\"Sheep (white)\"}],\"text\":\"\"}'},SkullOwner:{Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjMxZjljY2M2YjNlMzJlY2YxM2I4YTExYWMyOWNkMzNkMThjOTVmYzczZGI4YTY2YzVkNjU3Y2NiOGJlNzAifX19\"}]},Id:[I;67411088,-739686879,-1666252800,11182900]}},Count:1b}",
            "entities": [
              "minecraft:sheep"
            ]
          }
        },
        {
          "id": "pet_chicken",
          "displayName": "Starte eine Hühnerzucht!",
          "goal": 5,
          "type": "BreedEntityObjective",
          "options": {
            "display": "{DataVersion:2586,id:\"minecraft:player_head\",tag:{Damage:3,display:{Name:'{\"extra\":[{\"bold\":false,\"italic\":false,\"underlined\":false,\"strikethrough\":false,\"obfuscated\":false,\"color\":\"blue\",\"text\":\"Chick\"}],\"text\":\"\"}'},SkullOwner:{Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTRkODE2YTQ3NWIzZjMxM2I2MjBkNjViZjkzNTg5MzFiNDZhZjljOGY0ZTdjOWFlNjQ3MDg4ODBiZWE2YmUifX19\"}]},Id:[I;67411088,-739686879,-1666252800,178930279]}},Count:1b}",
            "entities": [
              "minecraft:chicken"
            ]
          }
        }
      ]
    }
  ],
  "requirements": [
    {
      "id": "req_1",
      "type": "QuestCompletedRequirement",
      "options": {
        "quests": [
          "1a_ressources",
          "1b_iron"
        ]
      }
    }
  ],
  "rewards": [
    {
      "id": "moneyreward",
      "displayName": "40 Münzen",
      "type": "TransactionReward",
      "options": {
        "amount": 40.0
      }
    }
  ]
}

=== Cytooxien/Cytooxien-Missions/quests/exampleBundle/template.json
{
  "id": "template1",
  "displayName": "Template 1",
  "description": "Template 2",
  "stages": [
    {
      "objectives": [
        {
          "id": "task1",
          "displayName": "Spawn",
          "type": "ActionEventObjective",
          "goal": 10,
          "options": {
            "action": "spawn"
          }
        }
      ]
    }
  ],
  "rewards": [
    {
      "id": "reward1",
      "displayName": "10$ Belohnung",
      "type": "TransactionReward",
      "options": {
        "amount": 10.0
      }
    }
  ]
}
